# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('start_date', models.DateField(verbose_name='Дата')),
                ('end_date', models.DateField(verbose_name='Завершение')),
                ('category', models.SlugField(choices=[('secondment', 'Командировка'), ('vacation', 'Отпуск')], verbose_name='Тип')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Календарь (hr)',
                'verbose_name_plural': 'Календарь (hr)',
                'ordering': ['-id'],
            },
        ),
    ]
