# Generated by Django 4.2.17 on 2026-04-21 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_employee_options'),
        ('hr', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('enbek_id', models.CharField(max_length=100, unique=True, verbose_name='ID Enbek')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacations', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отпуск (Enbek)',
                'verbose_name_plural': 'Отпуска (Enbek)',
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа')),
                ('enbek_id', models.CharField(max_length=100, unique=True, verbose_name='ID Enbek')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sick_leaves', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Больничный (Enbek)',
                'verbose_name_plural': 'Больничные (Enbek)',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('enbek_id', models.CharField(max_length=100, unique=True, verbose_name='ID Enbek')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_contracts', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Трудовой договор (Enbek)',
                'verbose_name_plural': 'Трудовые договоры (Enbek)',
            },
        ),
    ]
