# Generated by Django 4.2.17 on 2026-04-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('working', 'Рабочий'), ('weekend', 'Выходной'), ('holiday', 'Праздник')], default='working', max_length=20, verbose_name='Тип дня')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='hr.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Производственный календарь',
                'verbose_name_plural': 'Производственный календарь',
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
