# Generated by Django 4.2.17 on 2026-04-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_workcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcalendar',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_calendars', to='hr.company', verbose_name='Компания'),
        ),
    ]
