# Generated by Django 4.2.17 on 2026-04-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
        ('hr', '0005_alter_workcalendar_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Оплачиваемый')),
                ('max_days_per_year', models.PositiveIntegerField(default=24, verbose_name='Макс. дней в году')),
            ],
            options={
                'verbose_name': 'Тип отпуска',
                'verbose_name_plural': 'Типы отпусков',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('working_days_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Количество рабочих дней')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус')),
                ('external_enbek_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в Enbek')),
                ('sync_status', models.CharField(default='local', max_length=20, verbose_name='Статус синхронизации')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='account.employee', verbose_name='Кто одобряет')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='account.employee', verbose_name='Сотрудник')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype', verbose_name='Тип отпуска')),
            ],
            options={
                'verbose_name': 'Заявка на отпуск',
                'verbose_name_plural': 'Заявки на отпуск',
            },
        ),
    ]
