# Generated by Django 4.2.17 on 2026-05-05 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
        ('hr', '0007_merge_20260504_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('day_start', 'Приход (начало дня)'), ('lunch_start', 'Начало обеда'), ('lunch_end', 'Конец обеда'), ('day_end', 'Уход (конец дня)')], max_length=20, verbose_name='Тип события')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance/%Y/%m/%d/', verbose_name='Фотофиксация')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('workstation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочая станция')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись посещаемости',
                'verbose_name_plural': 'Записи посещаемости',
                'ordering': ['-timestamp'],
            },
        ),
    ]
