# Generated by Django 4.2.17 on 2026-05-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
        ('hr', '0009_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (РУ)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Название (EN)')),
                ('category_group', models.CharField(max_length=100, verbose_name='Группа')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=20, verbose_name='Уровень риска')),
                ('requires_training', models.BooleanField(default=True, verbose_name='Требуется обучение')),
                ('requires_medical_exam', models.BooleanField(default=False, verbose_name='Требуется медосмотр')),
                ('requires_ptw', models.BooleanField(default=False, verbose_name='Требуется наряд-допуск (PTW)')),
                ('requires_ppe', models.BooleanField(default=False, verbose_name='Требуется СИЗ')),
                ('requires_gas_test', models.BooleanField(default=False, verbose_name='Требуется газоанализ')),
                ('requires_supervisor', models.BooleanField(default=False, verbose_name='Требуется супервайзер')),
                ('requires_license', models.BooleanField(default=False, verbose_name='Требуется гос. лицензия/удостоверение')),
                ('certificate_validity_months', models.PositiveIntegerField(default=12, verbose_name='Срок сертификата (мес)')),
                ('required_ppe', models.JSONField(blank=True, default=list, verbose_name='Список СИЗ')),
                ('related_regulations', models.JSONField(blank=True, default=list, verbose_name='Нормативные акты')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Справочник категорий',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(verbose_name='Дата истечения')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер удостоверения/допуска')),
                ('scan', models.FileField(blank=True, null=True, upload_to='hr/permits/', verbose_name='Скан документа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permits', to='hr.workcategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permits', to='account.employee')),
            ],
            options={
                'verbose_name': 'Допуск сотрудника',
                'verbose_name_plural': 'Допуски сотрудников',
                'unique_together': {('employee', 'category')},
            },
        ),
    ]
