# Generated by Django 4.2.17 on 2026-05-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_attendancerecord_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('expiring', 'Истекает'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
