# Generated by Django 4.2.17 on 2026-05-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employeecertification_cert_type_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecertification',
            name='cert_type',
            field=models.CharField(max_length=255, verbose_name='Тип сертификации'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('confirmed', 'Подтверждено'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
