# Generated by Django 4.2.17 on 2026-06-05 07:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_tenant_portal'),
        ('hr', '0017_alter_employeecertification_cert_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Начало рабочего дня')),
                ('work_end', models.TimeField(default=datetime.time(18, 0), verbose_name='Конец рабочего дня')),
                ('lunch_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('lunch_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='Допустимое опоздание, мин')),
                ('workdays', models.CharField(default='0,1,2,3,4', help_text='Номера дней через запятую: 0=Пн … 6=Вс', max_length=20, verbose_name='Рабочие дни недели')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
    ]
