# Generated by Django 4.2.17 on 2026-08-12 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0019_disable_lunch_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceManualReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Основание ручной отметки',
                'verbose_name_plural': 'Основания ручных отметок',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Ручная отметка'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='manual_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор ручной отметки'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='manual_comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='manual_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.attendancemanualreason', verbose_name='Основание'),
        ),
    ]
