# Generated by Django 4.2.17 on 2026-08-12 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0020_attendancemanualreason_attendancerecord_is_manual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=16, verbose_name='Действие')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='До')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='После')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_edit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='hr.attendancerecord', verbose_name='Отметка')),
            ],
            options={
                'verbose_name': 'Лог изменения отметки',
                'verbose_name_plural': 'Логи изменений отметок',
                'ordering': ['-created_at'],
            },
        ),
    ]
