# Generated by Django 4.2.17 on 2026-08-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_attendanceeditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceeditlog',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='hr.attendancerecord', verbose_name='Отметка'),
        ),
    ]
