# Generated by Django 4.2.17 on 2026-08-27 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0022_alter_attendanceeditlog_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qr_points', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'QR-точка',
                'verbose_name_plural': 'QR-точки',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('face', 'Фотофиксация'), ('qr', 'QR-код'), ('manual', 'Ручная отметка')], default='face', max_length=16, verbose_name='Источник отметки'),
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('event_type', models.CharField(choices=[('day_start', 'Приход (начало дня)'), ('lunch_start', 'Начало обеда'), ('lunch_end', 'Конец обеда'), ('day_end', 'Уход (конец дня)')], max_length=32, verbose_name='Тип отметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('qr_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='hr.qrpoint', verbose_name='QR-точка')),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_qr_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Использован кем')),
            ],
            options={
                'verbose_name': 'QR-токен',
                'verbose_name_plural': 'QR-токены',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScanAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
                ('action', models.CharField(choices=[('success', 'Успешно'), ('expired', 'Истёк'), ('replay', 'Повторное использование'), ('invalid', 'Невалидный токен')], max_length=16, verbose_name='Результат')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_audits', to='hr.qrpoint', verbose_name='QR-точка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scan_audits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аудит QR-сканирования',
                'verbose_name_plural': 'Аудит QR-сканирований',
                'ordering': ['-created_at'],
            },
        ),
    ]
