# Generated by Django 4.0.3 on 2023-09-24 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.SlugField(choices=[('administrator', 'Администратор'), ('staff', 'Сотрудник'), ('guest', 'Гость')], verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.SlugField(choices=[('system_log', 'Активность'), ('staff', 'Для сотрудников'), ('default', 'Уведомление')], verbose_name='Тип уведомления')),
                ('readed', models.BooleanField(default=False, verbose_name='Прочитан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-id'],
            },
        ),
    ]
