# Generated by Django 4.0.3 on 2023-10-01 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_useraccount_role_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='readed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
