# Generated by Django 4.0.3 on 2023-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_notification_readed_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Отправлен'),
        ),
    ]
