# Generated by Django 4.0.3 on 2023-10-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_notification_sended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
    ]
