# Generated by Django 4.0.3 on 2023-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Идентификатор объекта'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тип объекта'),
        ),
    ]
