# Generated by Django 4.0.3 on 2023-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_notification_target_id_notification_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта'),
        ),
    ]
