# Generated by Django 4.0.3 on 2024-12-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_notification_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='Идентификатор объекта')),
                ('target_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип объекта')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_indicator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Индикатор уведомлений',
                'verbose_name_plural': 'Индикаторы уведомлений',
                'ordering': ['-id'],
            },
        ),
    ]
