# Generated by Django 4.2.17 on 2026-04-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_company'),
        ('account', '0009_notificationindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='hr.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='department',
            name='level_type',
            field=models.CharField(choices=[('department', 'Department'), ('division', 'Division')], default='department', max_length=20, verbose_name='Тип уровня'),
        ),
    ]
