# Generated by Django 4.2.17 on 2026-04-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_employee_options_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-head', 'user__last_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
