# Generated by Django 4.2.17 on 2026-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.SlugField(choices=[('administrator', 'Администратор'), ('staff', 'Сотрудник'), ('guest', 'Гость'), ('owner', 'Владелец'), ('cfo', 'Финансовый директор'), ('chief_accountant', 'Главный бухгалтер')], verbose_name='Роль'),
        ),
    ]
