# Generated by Django 4.2.17 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.SlugField(choices=[('administrator', 'Администратор'), ('hr', 'HR-менеджер'), ('staff', 'Сотрудник'), ('guest', 'Гость'), ('owner', 'Владелец'), ('cfo', 'Финансовый директор'), ('chief_accountant', 'Главный бухгалтер')], verbose_name='Роль'),
        ),
    ]
