# Generated by Django 4.2.17 on 2026-06-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_date_notify'),
        ('account', '0017_add_hr_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.tenant', verbose_name='Арендатор'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.SlugField(choices=[('administrator', 'Администратор'), ('hr', 'HR-менеджер'), ('staff', 'Сотрудник'), ('guest', 'Гость'), ('owner', 'Владелец'), ('cfo', 'Финансовый директор'), ('chief_accountant', 'Главный бухгалтер'), ('tenant', 'Арендатор')], verbose_name='Роль'),
        ),
    ]
