# Generated by Django 4.2.17 on 2026-05-28 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_add_hr_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_global', models.BooleanField(default=False, help_text='Если включено — контрагенты этого типа видят все пользователи.', verbose_name='Доступен всем авторизованным')),
                ('roles', models.JSONField(blank=True, default=list, help_text='Список slug ролей (administrator, staff, …).', verbose_name='Роли')),
                ('departments', models.ManyToManyField(blank=True, related_name='access_scopes', to='account.department', verbose_name='Отделы')),
                ('users', models.ManyToManyField(blank=True, related_name='access_scopes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Зона доступа',
                'verbose_name_plural': 'Зоны доступа',
                'ordering': ['name'],
            },
        ),
    ]
