# Generated by Django 4.2.17 on 2026-08-06 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_tenant_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('category', models.CharField(default='general', max_length=32, verbose_name='Категория')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Разрешить'), ('DENY', 'Запретить')], max_length=8, verbose_name='Эффект')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем задано')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='account.apppermission', verbose_name='Право')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Индивидуальное право',
                'verbose_name_plural': 'Индивидуальные права',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название профиля')),
                ('role', models.SlugField(blank=True, max_length=32, null=True, unique=True, verbose_name='Роль')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный профиль')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('permissions', models.ManyToManyField(blank=True, related_name='profiles', to='account.apppermission', verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Профиль прав',
                'verbose_name_plural': 'Профили прав',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='userpermissionoverride',
            constraint=models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission_override'),
        ),
    ]
