# Generated by Django 4.2.17 on 2026-08-07 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_apppermission_userpermissionoverride_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('role', 'По роли'), ('department', 'По отделу')], max_length=16, verbose_name='Тип группы')),
                ('role', models.SlugField(blank=True, max_length=32, null=True, verbose_name='Роль')),
                ('can_delegate', models.BooleanField(default=False, verbose_name='Разрешена делегация')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначено')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='account.department', verbose_name='Отдел')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='account.permissionprofile', verbose_name='Профиль прав')),
            ],
            options={
                'verbose_name': 'Назначение профиля',
                'verbose_name_plural': 'Назначения профилей',
                'ordering': ['scope_type'],
            },
        ),
    ]
