# Generated by Django 4.2.17 on 2026-08-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_profile_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermission',
            name='block',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='apppermission',
            name='operation',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Операция'),
        ),
    ]
