# Generated by Django 4.2.17 on 2026-08-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_permission_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANT', 'Выдано право профилю'), ('REVOKE', 'Отозвано право у профиля'), ('OVERRIDE_ADD', 'Добавлено индивидуальное переопределение'), ('OVERRIDE_CHANGE', 'Изменено индивидуальное переопределение'), ('OVERRIDE_DELETE', 'Удалено индивидуальное переопределение')], max_length=32, verbose_name='Действие')),
                ('permission_code', models.CharField(blank=True, max_length=64, verbose_name='Код права')),
                ('effect', models.CharField(blank=True, max_length=8, verbose_name='Эффект')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='account.permissionprofile', verbose_name='Профиль')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL, verbose_name='На кого влияет')),
            ],
            options={
                'verbose_name': 'Лог аудита прав',
                'verbose_name_plural': 'Лог аудита прав',
                'ordering': ['-created_at'],
            },
        ),
    ]
