# Generated by Django 4.2.17 on 2026-08-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_permissionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionauditlog',
            name='after',
            field=models.JSONField(blank=True, null=True, verbose_name='После'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='before',
            field=models.JSONField(blank=True, null=True, verbose_name='До'),
        ),
    ]
