# Generated by Django 4.2.17 on 2026-08-11 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_permissionauditlog_after_permissionauditlog_before'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=32, verbose_name='Старый статус')),
                ('new_status', models.CharField(max_length=32, verbose_name='Новый статус')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Лог изменения статуса',
                'verbose_name_plural': 'Логи изменения статуса',
                'ordering': ['-created_at'],
            },
        ),
    ]
