# Generated by Django 4.2.17 on 2026-08-14 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_employeestatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_users', to='account.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
