# Generated by Django 4.2.17 on 2026-08-28 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_notificationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истёк')], default='active', max_length=16, verbose_name='Статус')),
                ('date_from', models.DateTimeField(verbose_name='Начало действия')),
                ('date_to', models.DateTimeField(verbose_name='Окончание действия')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_temporary_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_accesses', to='account.apppermission', verbose_name='Право')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_temporary_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Отозвал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Временный доступ',
                'verbose_name_plural': 'Временные доступы',
                'ordering': ['-created_at'],
            },
        ),
    ]
