# Generated by Django 4.2.17 on 2026-10-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_officeqrpoint'),
        ('account', '0028_temporaryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileassignment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_assignments', to='hr.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profileassignment',
            name='scope_type',
            field=models.CharField(choices=[('role', 'По роли'), ('department', 'По отделу'), ('position', 'По должности')], max_length=16, verbose_name='Тип группы'),
        ),
    ]
