# Generated by Django 4.2.17 on 2026-05-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_date_notify'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPaymentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('period', models.DateField(verbose_name='Период (месяц/год)')),
                ('charged', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Начислено')),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Оплачено')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Задолженность')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата оплаты')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата оплаты')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Дней просрочки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('partial', 'Частично оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('onec_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_registry', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Платёж арендатора',
                'verbose_name_plural': 'Реестр платежей арендаторов',
                'ordering': ['-period', 'tenant'],
                'indexes': [models.Index(fields=['status'], name='finances_te_status_3fe64d_idx'), models.Index(fields=['period'], name='finances_te_period_22c42d_idx'), models.Index(fields=['tenant', 'period'], name='finances_te_tenant__f7ac13_idx')],
                'unique_together': {('tenant', 'contract_number', 'period')},
            },
        ),
    ]
