# Generated by Django 4.2.17 on 2026-05-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_date_notify'),
        ('finances', '0002_tenantpaymentregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('expected_date', models.DateField(verbose_name='Плановая дата оплаты')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Плановая сумма')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Фактическая сумма')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата оплаты')),
                ('status', models.CharField(choices=[('plan', 'План'), ('fact', 'Факт'), ('overdue', 'Просрочен')], db_index=True, default='plan', max_length=10, verbose_name='Статус')),
                ('onec_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_calendar', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Запись календаря платежей',
                'verbose_name_plural': 'Календарь платежей',
                'ordering': ['expected_date', 'tenant'],
                'indexes': [models.Index(fields=['expected_date'], name='finances_pa_expecte_54b4a8_idx'), models.Index(fields=['status'], name='finances_pa_status_eddafb_idx'), models.Index(fields=['tenant', 'expected_date'], name='finances_pa_tenant__57e723_idx')],
                'unique_together': {('tenant', 'contract_number', 'expected_date')},
            },
        ),
    ]
