# Generated by Django 4.2.17 on 2026-05-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0005_alter_invoice_options_invoice_comment_and_more'),
        ('tenants', '0006_tenant_date_notify'),
        ('finances', '0003_paymentcalendarentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер счёта')),
                ('period', models.DateField(blank=True, null=True, verbose_name='Период')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер договора')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='НДС')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], db_index=True, default='created', max_length=20, verbose_name='Статус')),
                ('sent_via', models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('manual', 'Вручную')], max_length=20, null=True, verbose_name='Способ отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('onec_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счёта в 1С')),
                ('onec_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус в 1С')),
                ('onec_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_invoices', to='onec.counterparty', verbose_name='Контрагент')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_invoices', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Выставленный счёт',
                'verbose_name_plural': 'Выставленные счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5, verbose_name='Ставка НДС %')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма НДС')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.generatedinvoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Позиция счёта',
                'verbose_name_plural': 'Позиции счёта',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='generatedinvoice',
            index=models.Index(fields=['status'], name='finances_ge_status_ad835f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedinvoice',
            index=models.Index(fields=['period'], name='finances_ge_period_901e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedinvoice',
            index=models.Index(fields=['tenant', 'period'], name='finances_ge_tenant__5b41fb_idx'),
        ),
    ]
