# Generated by Django 4.2.17 on 2026-05-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_generatedinvoice_generatedinvoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], db_index=True, max_length=10, verbose_name='Тип')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finances.budgetcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория бюджета',
                'verbose_name_plural': 'Категории бюджета',
                'ordering': ['category_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Месяц'), ('quarterly', 'Квартал'), ('yearly', 'Год')], default='monthly', max_length=10, verbose_name='Тип периода')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц (1-12)')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартал (1-4)')),
                ('plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='План')),
                ('fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Факт')),
                ('forecast', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Прогноз')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finances.budgetcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Строка бюджета',
                'verbose_name_plural': 'Строки бюджета',
                'ordering': ['year', 'month', 'quarter', 'category'],
                'indexes': [models.Index(fields=['year', 'month'], name='finances_bu_year_26724a_idx'), models.Index(fields=['year', 'quarter'], name='finances_bu_year_b8a88f_idx'), models.Index(fields=['category', 'year'], name='finances_bu_categor_4f656c_idx')],
                'unique_together': {('category', 'period_type', 'year', 'month', 'quarter')},
            },
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['category_type'], name='finances_bu_categor_f0a3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['parent'], name='finances_bu_parent__f8b5de_idx'),
        ),
    ]
