# Generated by Django 4.2.17 on 2026-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_budgetcategory_budgetitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Месяц'), ('quarterly', 'Квартал'), ('yearly', 'Год')], db_index=True, default='monthly', max_length=10, verbose_name='Тип периода')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Месяц (1-12)')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартал (1-4)')),
                ('revenue_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Выручка план')),
                ('revenue_fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Выручка факт')),
                ('revenue_forecast', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Выручка прогноз')),
                ('ebitda_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='EBITDA план')),
                ('ebitda_fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='EBITDA факт')),
                ('ebitda_forecast', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='EBITDA прогноз')),
                ('operating_profit_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Операционная прибыль план')),
                ('operating_profit_fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Операционная прибыль факт')),
                ('net_profit_plan', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Чистая прибыль план')),
                ('net_profit_fact', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Чистая прибыль факт')),
                ('net_profit_forecast', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Чистая прибыль прогноз')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_categories', models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'expense'}, related_name='expense_statements', to='finances.budgetcategory', verbose_name='Категории расходов')),
                ('revenue_categories', models.ManyToManyField(blank=True, limit_choices_to={'category_type': 'income'}, related_name='revenue_statements', to='finances.budgetcategory', verbose_name='Категории выручки')),
            ],
            options={
                'verbose_name': 'Отчёт ОПиУ',
                'verbose_name_plural': 'Отчёты ОПиУ',
                'ordering': ['-year', '-month', '-quarter'],
                'indexes': [models.Index(fields=['year', 'month'], name='finances_fi_year_3211a0_idx'), models.Index(fields=['period_type', 'year'], name='finances_fi_period__4c52ce_idx')],
                'unique_together': {('period_type', 'year', 'month', 'quarter')},
            },
        ),
    ]
