# Generated by Django 4.2.17 on 2026-05-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0005_alter_invoice_options_invoice_comment_and_more'),
        ('finances', '0006_financialstatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inflow', 'Поступление'), ('outflow', 'Списание')], db_index=True, max_length=10, verbose_name='Направление')),
                ('flow_type', models.CharField(choices=[('operating', 'Операционная деятельность'), ('investing', 'Инвестиционная деятельность'), ('financing', 'Финансовая деятельность')], db_index=True, default='operating', max_length=15, verbose_name='Тип деятельности')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма')),
                ('currency', models.CharField(default='KZT', max_length=3, verbose_name='Валюта')),
                ('transaction_date', models.DateField(db_index=True, verbose_name='Дата операции')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Дата валютирования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Назначение платежа')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа')),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Банковский счёт')),
                ('onec_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID в 1С')),
                ('onec_document_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип документа 1С')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_records', to='finances.budgetcategory', verbose_name='Статья бюджета')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_records', to='onec.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Запись ДДС',
                'verbose_name_plural': 'Реестр ДДС',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='finances_ca_transac_01226c_idx'), models.Index(fields=['direction'], name='finances_ca_directi_ce4d64_idx'), models.Index(fields=['flow_type'], name='finances_ca_flow_ty_f78404_idx'), models.Index(fields=['counterparty'], name='finances_ca_counter_4ebecf_idx'), models.Index(fields=['budget_category'], name='finances_ca_budget__58e98e_idx'), models.Index(fields=['transaction_date', 'direction'], name='finances_ca_transac_07740c_idx')],
            },
        ),
    ]
