# Generated by Django 4.2.17 on 2026-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_cashflowrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Курс к KZT')),
                ('source', models.CharField(default='nbrk', max_length=50, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency'],
                'indexes': [models.Index(fields=['date'], name='finances_ex_date_9910e2_idx'), models.Index(fields=['currency', 'date'], name='finances_ex_currenc_2bc3fa_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
