# Generated by Django 4.2.17 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_cashflowrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('scenario', models.CharField(choices=[('base', 'Базовый'), ('stress', 'Стресс'), ('optimistic', 'Оптимистичный')], default='base', max_length=20, verbose_name='Сценарий')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('projected_income', models.JSONField(default=dict, verbose_name='Прогноз доходов')),
                ('projected_expenses', models.JSONField(default=dict, verbose_name='Прогноз расходов')),
                ('projected_cashflow', models.JSONField(default=dict, verbose_name='Прогноз ДДС')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма кредита')),
                ('loan_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ставка, %')),
                ('dscr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='DSCR')),
                ('free_cashflow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Свободный CF')),
                ('risk_level', models.CharField(default='medium', max_length=20, verbose_name='Уровень риска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кредитная модель',
                'verbose_name_plural': 'Кредитные модели',
                'ordering': ['-created_at'],
            },
        ),
    ]
