# Generated by Django 4.2.17 on 2026-05-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_cashflowrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('scenario', models.CharField(choices=[('base', 'Базовый'), ('stress', 'Стрессовый'), ('optimistic', 'Оптимистичный')], db_index=True, default='base', max_length=15, verbose_name='Сценарий')),
                ('year', models.PositiveIntegerField(db_index=True, verbose_name='Год прогноза')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Сумма кредита')),
                ('loan_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Процентная ставка %')),
                ('loan_term_months', models.PositiveIntegerField(default=12, verbose_name='Срок кредита (мес)')),
                ('annual_debt_service', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Годовое обслуживание долга')),
                ('forecast_pnl', models.JSONField(blank=True, default=dict, help_text='{"revenue": 0, "ebitda": 0, "operating_profit": 0, "net_profit": 0}', verbose_name='Прогнозный ОПиУ')),
                ('forecast_cashflow', models.JSONField(blank=True, default=dict, help_text='{"operating": 0, "investing": 0, "financing": 0, "free_cashflow": 0}', verbose_name='Прогнозный Cash Flow')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], db_index=True, default='medium', max_length=10, verbose_name='Уровень риска')),
                ('risk_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий по рискам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_models', to='finances.financialstatement', verbose_name='Отчёт ОПиУ')),
            ],
            options={
                'verbose_name': 'Кредитная модель',
                'verbose_name_plural': 'Кредитные модели',
                'ordering': ['-year', 'scenario'],
                'indexes': [models.Index(fields=['scenario'], name='finances_cr_scenari_b2bf10_idx'), models.Index(fields=['risk_level'], name='finances_cr_risk_le_f82bf2_idx'), models.Index(fields=['year', 'scenario'], name='finances_cr_year_f355f5_idx')],
                'unique_together': {('name', 'scenario', 'year')},
            },
        ),
    ]
