# Generated by Django 4.2.17 on 2026-05-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_creditmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='ISO 4217, например: USD, EUR, RUB', max_length=10, verbose_name='Код валюты')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Курс к KZT')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency'],
                'indexes': [models.Index(fields=['currency', 'date'], name='finances_ex_currenc_2bc3fa_idx'), models.Index(fields=['date'], name='finances_ex_date_9910e2_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
