# Generated by Django 4.2.17 on 2026-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_financialstatement_onec_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (англ)'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (каз)'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название (рус)'),
        ),
    ]
