# Generated by Django 4.2.17 on 2026-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_creditmodel_uat05_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedinvoice',
            name='sent_via',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('manual', 'Вручную')], max_length=20, null=True, verbose_name='Способ отправки'),
        ),
    ]
