# Generated by Django 4.2.17 on 2026-06-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_budgetcategory_name_en_budgetcategory_name_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='budgetcategory',
            name='name_ru',
        ),
    ]
