# Generated by Django 4.2.17 on 2026-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_generatedinvoice_sent_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedinvoice',
            name='sent_via',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('manual', 'Вручную')], max_length=20, null=True, verbose_name='Способ отправки'),
        ),
    ]
