# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория контрагента',
                'verbose_name_plural': 'Категории контрагента',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.SlugField(choices=[('moderated', 'На модерации'), ('checked', 'Проверен'), ('refused', 'Отказано')], verbose_name='Статус')),
                ('check_status', models.SlugField(blank=True, choices=[('reliable', 'Благонадежный'), ('reliable', 'Неблагонадежный')], null=True, verbose_name='Результат проверки')),
                ('form', models.SlugField(blank=True, choices=[('too', 'ТОО'), ('ip', 'ИП')], null=True, verbose_name='Форма собственности')),
                ('supplier_type', models.SlugField(blank=True, choices=[('individual', 'Физ. лицо'), ('legal', 'Юр. лицо')], null=True, verbose_name='Юр./физ. лицо')),
                ('reg_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('identifier', models.CharField(blank=True, max_length=40, null=True, verbose_name='БИН/ИИН')),
                ('kbe', models.CharField(blank=True, max_length=40, null=True, verbose_name='КБЕ')),
                ('address1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Юр. адрес')),
                ('address2', models.CharField(max_length=60, verbose_name='Фактический адрес')),
                ('head_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='ФИО учредителя')),
                ('head_status', models.CharField(blank=True, max_length=40, null=True, verbose_name='Статус учредителя')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('certificate_serie', models.CharField(blank=True, max_length=40, null=True, verbose_name='Серия свидетельства')),
                ('certificate_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер свидетельства')),
                ('certificate_date', models.CharField(blank=True, max_length=40, null=True, verbose_name='Дата свидетельства')),
                ('contacts', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакты')),
                ('adata_link', models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на карточку ADATA.KZ')),
                ('oked', models.CharField(blank=True, max_length=100, null=True, verbose_name='Основной ОКЭД')),
                ('name', models.CharField(max_length=100, verbose_name='Полное наименование')),
                ('problems', models.CharField(blank=True, max_length=100, null=True, verbose_name='Есть проблемы')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размер предприятия')),
                ('lawyer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юрист')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('category', models.ManyToManyField(blank=True, to='purchases.suppliercategory', verbose_name='Категории')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
    ]
