# Generated by Django 4.2.17 on 2026-07-23 06:25

from django.db import migrations, models


def copy_categories_to_text(apps, schema_editor):
    Supplier = apps.get_model('purchases', 'Supplier')
    for supplier in Supplier.objects.prefetch_related('category').iterator(chunk_size=500):
        value = ', '.join(supplier.category.order_by('title').values_list('title', flat=True))
        if len(value) > 200:
            raise RuntimeError(
                f'Supplier {supplier.pk} categories exceed 200 characters; '
                'migration stopped to avoid truncating data.'
            )
        supplier.category_text = value or None
        supplier.save(update_fields=['category_text'])


def restore_categories_from_text(apps, schema_editor):
    Supplier = apps.get_model('purchases', 'Supplier')
    SupplierCategory = apps.get_model('purchases', 'SupplierCategory')
    for supplier in Supplier.objects.exclude(category_text__isnull=True).iterator():
        categories = []
        for title in supplier.category_text.split(','):
            title = title.strip()
            if title:
                category, _ = SupplierCategory.objects.get_or_create(title=title)
                categories.append(category)
        supplier.category.set(categories)


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_supplier_onec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Категории'),
        ),
        migrations.RunPython(copy_categories_to_text, restore_categories_from_text),
        migrations.RemoveField(
            model_name='supplier',
            name='category',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='category_text',
            new_name='category',
        ),
    ]
