[pytest]
DJANGO_SETTINGS_MODULE = project.settings
pythonpath = .
testpaths = apps
python_files = tests.py test_*.py tests_*.py
norecursedirs = .git .venv migrations management static media assets templates
addopts =
    --cov=apps
    --cov-report=term-missing
    --cov-fail-under=70
    -q
