#!/usr/bin/env python3
"""
Собирает static/site/js/i18n-bundle.js из locale/*.json.
Словарь byText: русский текст страницы -> перевод (для kk/en).
Запуск: python scripts/build_i18n_bundle.py
"""
from __future__ import annotations

import json
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
LOCALE_DIR = BACKEND / 'apps' / 'account' / 'locale'
OUT = BACKEND / 'static' / 'site' / 'js' / 'i18n-bundle.js'
LANGS = ('ru', 'kk', 'en')


def _walk_strings(ru_node, kk_node, en_node, by_text: dict):
    if not isinstance(ru_node, dict):
        return
    for key, ru_val in ru_node.items():
        kk_val = kk_node.get(key) if isinstance(kk_node, dict) else None
        en_val = en_node.get(key) if isinstance(en_node, dict) else None
        if isinstance(ru_val, dict):
            _walk_strings(
                ru_val,
                kk_val if isinstance(kk_val, dict) else {},
                en_val if isinstance(en_val, dict) else {},
                by_text,
            )
        elif isinstance(ru_val, str) and _is_translatable(ru_val):
            ru_key = _norm(ru_val)
            if ru_key not in by_text:
                by_text[ru_key] = {'ru': ru_val}
            entry = by_text[ru_key]
            if isinstance(kk_val, str):
                entry['kk'] = kk_val
            if isinstance(en_val, str):
                entry['en'] = en_val


def _is_translatable(s: str) -> bool:
    s = s.strip()
    if len(s) < 2 or len(s) > 200:
        return False
    if any(c.isdigit() for c in s) and sum(c.isalpha() for c in s) < 3:
        return False
    return any('\u0400' <= c <= '\u04FF' or c in 'әғқңөұүіӘҒҚҢӨҰҮІ' for c in s)


def _norm(s: str) -> str:
    return ' '.join(s.split())


def _load_phrases(by_text: dict):
    path = LOCALE_DIR / 'phrases.json'
    if not path.exists():
        return
    for row in json.loads(path.read_text(encoding='utf-8')):
        ru_val = row.get('ru', '').strip()
        if not _is_translatable(ru_val):
            continue
        key = _norm(ru_val)
        by_text[key] = {
            'ru': ru_val,
            'kk': row.get('kk', ru_val),
            'en': row.get('en', ru_val),
        }


def main():
    ru = json.loads((LOCALE_DIR / 'ru.json').read_text(encoding='utf-8'))
    kk = json.loads((LOCALE_DIR / 'kk.json').read_text(encoding='utf-8'))
    en = json.loads((LOCALE_DIR / 'en.json').read_text(encoding='utf-8'))

    by_text: dict = {}
    _walk_strings(ru, kk, en, by_text)
    _load_phrases(by_text)

    for lang in ('kk', 'en'):
        for entry in by_text.values():
            if lang not in entry:
                entry[lang] = entry['ru']

    by_text_kk = {k: v['kk'] for k, v in by_text.items()}
    by_text_en = {k: v['en'] for k, v in by_text.items()}

    for entry in by_text.values():
        ru_val = entry['ru']
        kk_val = entry.get('kk', ru_val)
        en_val = entry.get('en', ru_val)

        if kk_val and kk_val != ru_val:
            kk_key = _norm(kk_val)
            if kk_key not in by_text_en:
                by_text_en[kk_key] = en_val
            if kk_key not in by_text_kk:
                by_text_kk[kk_key] = kk_val

        if en_val and en_val != ru_val:
            en_key = _norm(en_val)
            if en_key not in by_text_kk:
                by_text_kk[en_key] = kk_val
            if en_key not in by_text_en:
                by_text_en[en_key] = en_val

    all_keys = set(by_text.keys()) | set(by_text_kk.keys()) | set(by_text_en.keys())
    keys_sorted = sorted(all_keys, key=len, reverse=True)

    keys_sorted = sorted(by_text.keys(), key=len, reverse=True)

    payload = {
        'version': 1,
        'keysSorted': keys_sorted,
        'kk': by_text_kk,
        'en': by_text_en,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '/* Auto-generated by scripts/build_i18n_bundle.py — do not edit */\n'
        f'window.BPM_TRANSLATIONS = {json.dumps(payload, ensure_ascii=False, separators=(",", ":"))};\n',
        encoding='utf-8',
    )
    print(f'Wrote {OUT} ({len(by_text)} phrases)')


if __name__ == '__main__':
    main()
