# Generated by Django 4.2.17 on 2026-07-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignerSigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('esigner_document_id', models.CharField(max_length=64, verbose_name='ID документа в eSigner')),
                ('esigner_folder_id', models.CharField(max_length=64, verbose_name='ID папки в eSigner')),
                ('sign_hash', models.CharField(blank=True, max_length=64, verbose_name='Хэш ссылки на подписание')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SENT', 'Отправлен на подписание'), ('COMPLETED', 'Подписан'), ('ARCHIVED', 'Архив'), ('REVOKED', 'Отозван')], default='DRAFT', max_length=16, verbose_name='Статус')),
                ('signers', models.JSONField(blank=True, default=list, verbose_name='Подписанты')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='esigner_signed/', verbose_name='Подписанный PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Подписание eSigner',
                'verbose_name_plural': 'Подписания eSigner',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='esigner_esi_content_9d591b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='esignersigning',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_esigner_signing_per_object'),
        ),
    ]
