server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location = /invoice-admin {
        return 301 /invoice-admin/;
    }

    location /invoice-admin/ {
        try_files $uri $uri/ /invoice-admin/index.html;
    }

    location / {
        return 302 /invoice-admin/;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}
