#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/yernur/Desktop/trc-bpm/mobile"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/yernur/Desktop/trc-bpm/mobile/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/yernur/Desktop/trc-bpm/mobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=QkFTRV9VUkw9aHR0cHM6Ly85NC0xMzEtMjMwLTEwMS5zc2xpcC5pbw==,U0NSRUVOU0hPVFM9dHJ1ZQ==,U0NSRUVOU0hPVF9UT1VSPXRydWU=,U0NSRUVOU0hPVF9VU0VSPWFwcHJldmlldw==,U0NSRUVOU0hPVF9QQVNTPVJldmlldyEyMDI2TXg=,RkxVVFRFUl9WRVJTSU9OPTMuNDQuNQ==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049Zjk0ZjRmYzc2Yg==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ODM2NzVlZDI3Ng==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/yernur/Desktop/trc-bpm/mobile/.dart_tool/package_config.json"
