# Generated by Django 4.2.17 on 2026-04-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_department_company_department_level_type'),
        ('hr', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование должности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='account.department', verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'unique_together': {('title', 'department')},
            },
        ),
    ]
