# Generated by Django 4.2.17 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_vacation_sickleave_employmentcontract'),
        ('hr', '0006_leavetype_leaverequest'),
    ]

    operations = [
    ]
