# Generated by Django 4.2.17 on 2026-05-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
        ('hr', '0008_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('employment_contract', 'Трудовой договор'), ('nda', 'NDA'), ('liability_agreement', 'Договор о мат. ответственности'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('expired', 'Истёк'), ('revoked', 'Отозван')], default='draft', max_length=20, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_documents/%Y/%m/', verbose_name='Файл')),
                ('signed_at', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('external_enbek_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID в Enbek')),
                ('sync_status', models.CharField(default='local', max_length=20, verbose_name='Статус синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Документ сотрудника',
                'verbose_name_plural': 'Документы сотрудников',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'doc_type', 'version')},
            },
        ),
    ]
