# Generated by Django 4.2.17 on 2026-05-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_workcategory_employeeworkpermit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория работ', 'verbose_name_plural': 'Справочник категорий'},
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='workcategory',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeworkpermit',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер удостоверения'),
        ),
    ]
