# Generated by Django 4.2.17 on 2026-05-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_department_company_alter_department_name_and_more'),
        ('hr', '0011_alter_workcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Название (EN)')),
                ('issuing_body', models.CharField(blank=True, max_length=255, verbose_name='Выдающий орган')),
                ('validity_months', models.PositiveIntegerField(default=12, verbose_name='Срок действия (мес)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Обязательная')),
                ('related_regulations', models.JSONField(blank=True, default=list, verbose_name='Нормативные акты')),
            ],
            options={
                'verbose_name': 'Тип сертификации',
                'verbose_name_plural': 'Справочник сертификаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('issuing_body', models.CharField(blank=True, max_length=255, verbose_name='Выдающий орган')),
                ('scan', models.FileField(blank=True, null=True, upload_to='hr/certifications/', verbose_name='Скан')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Отозван')),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='hr.certificationtype', verbose_name='Тип сертификации')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='account.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сертификация сотрудника',
                'verbose_name_plural': 'Сертификации сотрудников',
                'ordering': ['-issue_date'],
            },
        ),
    ]
