"""Демо-контрагенты для разработки и демо без подключённой 1С."""

DEMO_COUNTERPARTIES = [
    {
        'id_1c': 'DEMO-001',
        'full_name': 'Товарищество с ограниченной ответственностью «Иллюминат»',
        'short_name': 'ТОО Иллюминат',
        'bin_number': '123456789012',
        'phone': '+7 727 111 22 33',
        'email': 'info@illuminat.kz',
        'address': 'г. Алматы, пр. Абая 150',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-002',
        'full_name': 'Акционерное общество «Казахтелеком»',
        'short_name': 'АО Казахтелеком',
        'bin_number': '234567890123',
        'phone': '+7 727 258 00 00',
        'email': 'contact@telecom.kz',
        'address': 'г. Алматы, ул. Каныша Сатпаева 32',
        'is_supplier': True,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-003',
        'full_name': 'Товарищество с ограниченной ответственностью «Cisco Kazakhstan»',
        'short_name': 'ТОО Cisco',
        'bin_number': '345678901234',
        'phone': '+7 727 244 55 66',
        'email': 'sales@cisco.kz',
        'address': 'г. Алматы, БЦ «Нурлы Тау»',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-004',
        'full_name': 'Индивидуальный предприниматель Калиева Айгуль Сериковна',
        'short_name': 'ИП Калиева',
        'bin_number': '456789012345',
        'iin': '900101350123',
        'phone': '+7 701 555 12 34',
        'email': 'kalieva@mail.kz',
        'address': 'г. Алматы, мкр. Самал-2',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-005',
        'full_name': 'Товарищество с ограниченной ответственностью «Рога и копыта»',
        'short_name': 'ТОО Рога и копыта',
        'bin_number': '567890123456',
        'phone': '+7 727 300 40 50',
        'email': 'office@roga.kz',
        'address': 'г. Алматы, ул. Жандосова 55',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-006',
        'full_name': 'Товарищество с ограниченной ответственностью «ТРЦ Сервис»',
        'short_name': 'ТОО ТРЦ Сервис',
        'bin_number': '678901234567',
        'phone': '+7 727 222 33 44',
        'email': 'service@trc.kz',
        'address': 'г. Алматы, ТРЦ MetriX',
        'is_supplier': False,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-007',
        'full_name': 'Товарищество с ограниченной ответственностью «Астана Электро»',
        'short_name': 'ТОО Астана Электро',
        'bin_number': '789012345678',
        'phone': '+7 717 250 60 70',
        'email': 'ae@electro.kz',
        'address': 'г. Астана, ул. Кенесары 40',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-008',
        'full_name': 'Товарищество с ограниченной ответственностью «CleanPro KZ»',
        'short_name': 'ТОО CleanPro',
        'bin_number': '890123456789',
        'phone': '+7 727 900 11 22',
        'email': 'hello@cleanpro.kz',
        'address': 'г. Алматы, ул. Розыбакиева 247',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-009',
        'full_name': 'Товарищество с ограниченной ответственностью «Magnum Cash&Carry»',
        'short_name': 'ТОО Magnum',
        'bin_number': '901234567890',
        'phone': '+7 727 330 44 55',
        'email': 'leasing@magnum.kz',
        'address': 'г. Алматы, пр. Райымбека 239',
        'is_supplier': False,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-010',
        'full_name': 'Товарищество с ограниченной ответственностью «Technodom Operator»',
        'short_name': 'ТОО Technodom',
        'bin_number': '012345678901',
        'phone': '+7 727 244 00 11',
        'email': 'b2b@technodom.kz',
        'address': 'г. Алматы, ул. Толе би 101',
        'is_supplier': False,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-011',
        'full_name': 'Товарищество с ограниченной ответственностью «Zara Kazakhstan»',
        'short_name': 'ТОО Zara KZ',
        'bin_number': '112233445566',
        'phone': '+7 727 255 66 77',
        'email': 'retail@zara.kz',
        'address': 'г. Алматы, ТРЦ MetriX, 1 этаж',
        'is_supplier': False,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-012',
        'full_name': 'Товарищество с ограниченной ответственностью «H&M Central Asia»',
        'short_name': 'ТОО H&M',
        'bin_number': '223344556677',
        'phone': '+7 727 255 88 99',
        'email': 'hm.leasing@hm.com',
        'address': 'г. Алматы, ТРЦ MetriX, 2 этаж',
        'is_supplier': False,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-013',
        'full_name': 'Товарищество с ограниченной ответственностью «Ventilation Pro»',
        'short_name': 'ТОО Ventilation Pro',
        'bin_number': '334455667788',
        'phone': '+7 701 222 33 44',
        'email': 'service@ventpro.kz',
        'address': 'г. Алматы, ул. Манаса 32',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-014',
        'full_name': 'Товарищество с ограниченной ответственностью «Security Group KZ»',
        'short_name': 'ТОО Security Group',
        'bin_number': '445566778899',
        'phone': '+7 727 390 12 00',
        'email': 'office@secgroup.kz',
        'address': 'г. Алматы, мкр. Орбита-4',
        'is_supplier': True,
        'is_customer': False,
    },
    {
        'id_1c': 'DEMO-015',
        'full_name': 'Товарищество с ограниченной ответственностью «Food Court Service»',
        'short_name': 'ТОО Food Court Service',
        'bin_number': '556677889900',
        'phone': '+7 727 311 22 33',
        'email': 'fcs@foodcourt.kz',
        'address': 'г. Алматы, ТРЦ MetriX, фудкорт',
        'is_supplier': True,
        'is_customer': True,
    },
    {
        'id_1c': 'DEMO-016',
        'full_name': 'Индивидуальный предприниматель Нурланов Болат Канатович',
        'short_name': 'ИП Нурланов',
        'bin_number': '667788990011',
        'iin': '850315300456',
        'phone': '+7 777 123 45 67',
        'email': 'nurlanov.b@mail.kz',
        'address': 'г. Алматы, ул. Шаляпина 12',
        'is_supplier': True,
        'is_customer': False,
    },
]
