# Generated by Django 4.0.3 on 2023-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantityRemainder', models.FloatField(blank=True, null=True, verbose_name='Остаток')),
                ('Nomenclature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номенклатура')),
                ('NomenclatureCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код номенклатуры')),
                ('Storehouse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Склад')),
                ('StorehouseCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код склада')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'ordering': ['NomenclatureCode'],
            },
        ),
    ]
