# Generated by Django 4.0.3 on 2023-10-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sum', models.FloatField(blank=True, null=True, verbose_name='Сумма')),
                ('Date', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('CounterpartyAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Счет контрагента')),
                ('OrganizationAccount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Счет компании')),
                ('PaymentType', models.CharField(blank=True, max_length=20, null=True, verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Расходы/доходы',
                'verbose_name_plural': 'Расходы/доходы',
                'ordering': ['id'],
            },
        ),
    ]
