# Generated by Django 4.0.3 on 2023-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0002_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='PaymentType',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Payment',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Тип платежа'),
        ),
    ]
