# Generated by Django 4.2.17 on 2026-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0003_remove_invoice_paymenttype_invoice_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1c', models.CharField(max_length=50, unique=True, verbose_name='ID 1C')),
                ('full_name', models.CharField(max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('bin_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='БИН')),
                ('iin', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Поставщик')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Клиент')),
                ('bank_accounts', models.JSONField(blank=True, default=list, verbose_name='Банковские счета')),
                ('contracts', models.JSONField(blank=True, default=list, verbose_name='Договоры')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['short_name'],
            },
        ),
    ]
