# Generated by Django 4.2.17 on 2026-04-22 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0004_counterparty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-Date'], 'verbose_name': 'Счет (Расходы/доходы)', 'verbose_name_plural': 'Счета (Расходы/доходы)'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='onec.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер счета'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('paid', 'Оплачен')], default='created', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара/услуги')),
                ('quantity', models.FloatField(default=1.0, verbose_name='Количество')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('total', models.FloatField(default=0.0, verbose_name='Итого')),
                ('vat_rate', models.FloatField(default=12.0, verbose_name='Ставка НДС (%)')),
                ('vat_amount', models.FloatField(default=0.0, verbose_name='Сумма НДС')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onec.invoice', verbose_name='Счет')),
            ],
            options={
                'verbose_name': 'Позиция счета',
                'verbose_name_plural': 'Позиции счета',
            },
        ),
    ]
