# Generated by Django 4.2.17 on 2026-05-29 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_add_hr_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onec', '0005_alter_invoice_options_invoice_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип контрагента',
                'verbose_name_plural': 'Типы контрагентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('roles', models.JSONField(blank=True, default=list, verbose_name='Роли')),
                ('counterparties', models.ManyToManyField(blank=True, related_name='access_scopes', to='onec.counterparty', verbose_name='Контрагенты')),
                ('counterparty_types', models.ManyToManyField(blank=True, related_name='access_scopes', to='onec.counterpartytype', verbose_name='Типы контрагентов')),
                ('departments', models.ManyToManyField(blank=True, related_name='access_scopes', to='account.department', verbose_name='Отделы')),
                ('users', models.ManyToManyField(blank=True, related_name='access_scopes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Зона доступа',
                'verbose_name_plural': 'Зоны доступа',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='counterparty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='onec.counterpartytype', verbose_name='Тип контрагента'),
        ),
    ]
