# Generated by Django 4.2.17 on 2026-05-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_counterparty_acl'),
        ('onec', '0005_alter_invoice_options_invoice_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('access_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_types', to='account.accessscope', verbose_name='Зона видимости')),
            ],
            options={
                'verbose_name': 'Тип контрагента',
                'verbose_name_plural': 'Типы контрагентов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='counterparty_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparties', to='onec.counterpartytype', verbose_name='Тип (зона доступа)'),
        ),
    ]
