# Generated by Django 4.2.17 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_seed_document_subfolders'),
        ('onec', '0006_counterpartytype_accessscope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessscope',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='access_scopes', to='documents.folder', verbose_name='Папки'),
        ),
    ]
