# Generated by Django 4.2.17 on 2026-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0006_counterparty_acl'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='activity_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид деятельности'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='founded_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата основания'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт / ссылка'),
        ),
    ]
