# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requistion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requistion_type', models.SlugField(choices=[('import', 'Ввоз'), ('export', 'Вывоз'), ('temp_pass', 'Временный пропуск'), ('perm_pass', 'Постоянный пропуск'), ('works', 'Проведение работ')], verbose_name='Тип заявки')),
                ('status', models.SlugField(choices=[('draft', 'Черновик'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('number', models.CharField(blank=True, max_length=120, null=True, verbose_name='Рег. №')),
                ('room', models.CharField(max_length=20, null=True, verbose_name='Помещение №')),
                ('route', models.CharField(max_length=100, null=True, verbose_name='Маршрут')),
                ('prop_list', models.TextField(null=True, verbose_name='Список имущества')),
                ('people_list', models.TextField(null=True, verbose_name='Список лиц')),
                ('start_date', models.DateField(null=True, verbose_name='Дата начала')),
                ('start_time', models.CharField(max_length=20, null=True, verbose_name='Время')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='ФИО')),
                ('role', models.CharField(max_length=50, null=True, verbose_name='Должность')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Адрес')),
                ('iin', models.CharField(max_length=50, null=True, verbose_name='ИИН')),
                ('coordinators', models.ManyToManyField(related_name='coordinator_requistions', to=settings.AUTH_USER_MODEL, verbose_name='Согласующие')),
                ('observers', models.ManyToManyField(related_name='observe_requistions', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='Контрагент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requistions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequistionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(choices=[('draft', 'Черновик'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('requistion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='requistions.requistion', verbose_name='Заявка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность заявки',
                'verbose_name_plural': 'Активность заявки',
                'ordering': ['-id'],
            },
        ),
    ]
