# Generated by Django 4.0.3 on 2023-09-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requistion',
            name='status',
            field=models.SlugField(choices=[('draft', 'Создан'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requistionhistory',
            name='status',
            field=models.SlugField(choices=[('draft', 'Создан'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус'),
        ),
    ]
