# Generated by Django 4.2.17 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requistions', '0002_alter_requistion_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requistion',
            name='requistion_type',
            field=models.SlugField(choices=[('import', 'Ввоз'), ('export', 'Вывоз'), ('temp_pass', 'Временный пропуск'), ('perm_pass', 'Постоянный пропуск'), ('works', 'Проведение работ'), ('repair', 'Ремонтные работы'), ('cleaning', 'Клининг'), ('incident', 'Инцидент / авария'), ('other', 'Прочее')], verbose_name='Тип заявки'),
        ),
    ]
