# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.SlugField(choices=[('documents', 'Документы'), ('purchases', 'Закупки'), ('budget', 'Бюджет')], verbose_name='Тип документа')),
                ('reg_date', models.DateField(null=True, verbose_name='Дата заполнения')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('status', models.SlugField(choices=[('draft', 'Черновик'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='Заголовок')),
                ('number', models.CharField(max_length=120, verbose_name='Рег. №')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('document', models.FileField(blank=True, null=True, upload_to=project.utils.PathAndRename('documents/'), verbose_name='Документ')),
                ('need_all', models.BooleanField(blank=True, default=True, verbose_name='Все должны согласовать')),
                ('need_head', models.BooleanField(blank=True, default=True, verbose_name='Требуется подпись главы')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('coordinators', models.ManyToManyField(related_name='coordinator_documents', to=settings.AUTH_USER_MODEL, verbose_name='Согласующие')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InnerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='Заголовок')),
                ('document', models.FileField(blank=True, null=True, upload_to=project.utils.PathAndRename('inner_documents/'), verbose_name='Документ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_documents', to='documents.document', verbose_name='Основной документ')),
            ],
            options={
                'verbose_name': 'Дополнительный документ',
                'verbose_name_plural': 'Дополнительные документы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('root_type', models.SlugField(blank=True, choices=[('documents', 'Документы'), ('purchases', 'Закупки'), ('budget', 'Бюджет')], null=True, unique=True, verbose_name='Тип папки (только для корневых)')),
                ('multiple_files', models.BooleanField(default=False, verbose_name='Несколько файлов в одном документе')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.folder')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(choices=[('draft', 'Черновик'), ('coordination', 'Согласование'), ('signing', 'Подписание'), ('active', 'Действующий'), ('archive', 'Архив')], verbose_name='Статус')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активность',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='document',
            name='observers',
            field=models.ManyToManyField(related_name='observe_documents', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
        migrations.AddField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='Контрагент'),
        ),
    ]
