# Generated by Django 4.2.17 on 2026-05-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_counterparty_acl'),
        ('documents', '0002_document_date_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='access_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='account.accessscope', verbose_name='Зона доступа'),
        ),
    ]
