# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('deadline', models.DateField(verbose_name='Срок')),
                ('status', models.SlugField(choices=[('to_do', 'На исполение'), ('doing', 'Выполняется'), ('done', 'Выполнено'), ('archive', 'Архив')], verbose_name='Статус')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текст')),
                ('important', models.BooleanField(blank=True, default=False, verbose_name='Важная задача')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('observers', models.ManyToManyField(related_name='observe_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
                ('responsible', models.ManyToManyField(related_name='responsible_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенные')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(choices=[('to_do', 'На исполение'), ('doing', 'Выполняется'), ('done', 'Выполнено'), ('archive', 'Архив')], verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активность',
                'ordering': ['id'],
            },
        ),
    ]
