# Generated by Django 4.2.17 on 2026-08-10 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Удалено в'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто удалил'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина удаления'),
        ),
    ]
