# Generated by Django 4.2.17 on 2026-04-15 10:55

from django.db import migrations, models


def migrate_priority(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        if task.important:
            task.priority = 'high'
        else:
            task.priority = 'medium'
        task.save(update_fields=['priority'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.SlugField(
                choices=[
                    ('low', 'Низкий'),
                    ('medium', 'Средний'),
                    ('high', 'Высокий'),
                    ('critical', 'Критический')
                ],
                default='medium',
                verbose_name='Приоритет'
            ),
        ),
        migrations.RunPython(migrate_priority),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SlugField(
                choices=[
                    ('created', 'Создана'),
                    ('accepted', 'Принята'),
                    ('rejected', 'Отклонена'),
                    ('revision', 'На доработке'),
                    ('completed', 'Завершена')
                ],
                verbose_name='Статус'
            ),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.SlugField(
                choices=[
                    ('created', 'Создана'),
                    ('accepted', 'Принята'),
                    ('rejected', 'Отклонена'),
                    ('revision', 'На доработке'),
                    ('completed', 'Завершена')
                ],
                verbose_name='Статус'
            ),
        ),
    ]