# Generated by Django 4.2.17 on 2026-04-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
    ]
