# Generated by Django 4.2.17 on 2026-04-16 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_responsible_to_executor(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')

    for task in Task.objects.all():
        responsibles = list(task.responsible.all())

        if responsibles:
            task.executor = responsibles[0]
            task.save(update_fields=['executor'])

            if len(responsibles) > 1:
                task.co_executors.set(responsibles[1:])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_remove_task_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(
                blank=True,
                related_name='co_executed_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Соисполнители'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='executed_tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнитель'
            ),
        ),
        migrations.RunPython(migrate_responsible_to_executor),
    ]