# Generated by Django 4.2.17 on 2026-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_co_executors_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
    ]
