# Generated by Django 4.2.17 on 2026-04-23 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_migrate_old_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='observe_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели'),
        ),
    ]
