# Generated by Django 4.2.17 on 2026-05-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0008_taskfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='important',
        ),
        migrations.RemoveField(
            model_name='task',
            name='responsible',
        ),
        migrations.AddField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, related_name='co_executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители'),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.SlugField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SlugField(choices=[('created', 'Создана'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('revision', 'На доработке'), ('completed', 'Завершена')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.SlugField(choices=[('created', 'Создана'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('revision', 'На доработке'), ('completed', 'Завершена')], verbose_name='Статус'),
        ),
    ]
