# Generated by Django 4.2.17 on 2026-05-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.SlugField(choices=[('assignment', 'Поручение'), ('approval', 'Согласование'), ('document', 'Документ')], default='assignment', verbose_name='Тип задачи'),
        ),
    ]
