# Generated by Django 4.2.17 on 2026-06-05 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_add_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Единица')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Позиция товара',
                'verbose_name_plural': 'Позиции товаров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Пункт')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Пункт чеклиста',
                'verbose_name_plural': 'Чеклист',
                'ordering': ['order', 'id'],
            },
        ),
    ]
