# Generated by Django 4.2.17 on 2026-06-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0005_alter_invoice_options_invoice_comment_and_more'),
        ('tasks', '0011_tasklineitem_taskchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='onec.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
