# Generated by Django 4.2.17 on 2026-06-05 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_task_extended_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUserFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.SlugField(choices=[('favorite', 'Избранное')], default='favorite', verbose_name='Флаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flags', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_flags', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пометка задачи',
                'verbose_name_plural': 'Пометки задач',
                'ordering': ['-id'],
                'unique_together': {('user', 'task', 'flag')},
            },
        ),
    ]
