# Generated by Django 4.2.17 on 2026-08-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_deleted_at_task_deleted_by_task_deleted_reason'),
        ('tasks', '0012_taskuserflag'),
    ]

    operations = [
    ]
