# Generated by Django 4.0.3 on 2023-03-31 02:13

from django.db import migrations, models
import django.db.models.deletion
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Категория арендаторов',
                'verbose_name_plural': 'Категории арендаторов',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=project.utils.PathAndRename('tenants/'), verbose_name='Фотография')),
                ('number', models.CharField(max_length=120, verbose_name='Номер помещения')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('note', models.TextField(blank=True, max_length=300, null=True, verbose_name='Примечание')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('price', models.FloatField(verbose_name='Ставка за кв2')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('phone', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('contact', models.CharField(max_length=40, verbose_name='Ответсвенное лицо')),
                ('start_date', models.DateField(null=True, verbose_name='Начало аренды')),
                ('end_date', models.DateField(null=True, verbose_name='Завершение аренды')),
                ('discount_date', models.DateField(null=True, verbose_name='Срок скидки')),
                ('percent', models.SmallIntegerField(default=0, verbose_name='Процент с оборота')),
                ('increase_type', models.SlugField(choices=[('step', 'Ступенчатая'), ('percent', 'Процентная')], null=True, verbose_name='Повышение ставки')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantcategory')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
                'ordering': ['name'],
            },
        ),
    ]
