# Generated by Django 4.0.3 on 2023-09-29 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер помещения')),
                ('map_id', models.CharField(max_length=30, verbose_name='Идентификатор на карте')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='number',
        ),
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.room', verbose_name='Помещение'),
        ),
    ]
