# Generated by Django 4.0.3 on 2023-09-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_room_remove_tenant_number_tenant_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='tenants.room', verbose_name='Помещение'),
        ),
    ]
