# Generated by Django 4.0.3 on 2023-09-29 11:00

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=project.utils.PathAndRename('tenant_icons/'), verbose_name='Иконка на карте'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=project.utils.PathAndRename('tenants/'), verbose_name='Фотография'),
        ),
    ]
