# Generated by Django 4.0.3 on 2023-10-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_icon_alter_tenant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantcategory', verbose_name='Категория'),
        ),
    ]
