# Generated by Django 4.0.3 on 2023-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='date_notify',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления о сроке'),
        ),
    ]
