# Generated by Django 4.2.17 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_date_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='map_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='Идентификатор на карте'),
        ),
    ]
