# Generated by Django 4.2.17 on 2026-07-16 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Эндпоинт')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP статус ответа')),
                ('response_body', models.JSONField(verbose_name='Тело ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ключ идемпотентности',
                'verbose_name_plural': 'Ключи идемпотентности',
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(fields=('key', 'user', 'endpoint'), name='unique_idempotency_key_per_user_endpoint'),
        ),
    ]
