# Generated by Django 4.2.17 on 2026-06-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoExecutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EcoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Объект')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EcoWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование работ')),
                ('responsible', models.CharField(blank=True, max_length=255, verbose_name='Ответственный')),
                ('document', models.FileField(blank=True, null=True, upload_to='ecopark/', verbose_name='Документ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('progress', 'В процессе'), ('done', 'Выполнен'), ('overdue', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(auto_now_add=True)),
                ('eco_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecopark.ecoobject', verbose_name='Объект')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecopark.ecoexecutor', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['-date'],
            },
        ),
    ]
