# Generated by Django 4.2.17 on 2026-08-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecopark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.CharField(max_length=255, verbose_name='Текст пункта')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пункт чек-листа',
                'verbose_name_plural': 'Пункты чек-листа',
                'ordering': ['point', 'order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('point_type', models.CharField(choices=[('electrical', 'Электрощитовая'), ('ventilation', 'Венткамера'), ('plumbing', 'Сантехнический узел'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Тип')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Расположение')),
                ('qr_code', models.CharField(blank=True, max_length=64, unique=True, verbose_name='QR-код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eco_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_points', to='ecopark.ecoobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Точка обхода',
                'verbose_name_plural': 'Точки обхода',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveIntegerField(default=4, verbose_name='Интервал (часов)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ecopark.inspectionpoint', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Расписание обхода',
                'verbose_name_plural': 'Расписания обходов',
            },
        ),
        migrations.CreateModel(
            name='InspectionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('missed', 'Пропущен')], default='pending', max_length=16, verbose_name='Статус')),
                ('server_time', models.DateTimeField(auto_now_add=True, verbose_name='Серверное время')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_rounds', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ecopark.inspectionpoint', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Обход',
                'verbose_name_plural': 'Обходы',
                'ordering': ['-server_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'Исправно'), ('defect', 'Неисправно'), ('skipped', 'Пропущено')], default='ok', max_length=16, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection/%Y/%m/%d/', verbose_name='Фото')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ecopark.checklistitem', verbose_name='Пункт чек-листа')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ecopark.inspectionround', verbose_name='Обход')),
            ],
            options={
                'verbose_name': 'Результат обхода',
                'verbose_name_plural': 'Результаты обхода',
                'unique_together': {('round', 'checklist_item')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='ecopark.inspectionpoint', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание неисправности')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Устранена')], default='open', max_length=16, verbose_name='Статус')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Эскалирован')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Устранён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defect', to='ecopark.inspectionresult', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Неисправность',
                'verbose_name_plural': 'Неисправности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='ecopark.inspectionpoint', verbose_name='Точка'),
        ),
    ]
