# Generated by Django 4.2.17 on 2026-09-07 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0028_temporaryaccess'),
        ('ecopark', '0005_round_point_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('substitute_from', models.DateTimeField(blank=True, null=True, verbose_name='Заместитель с')),
                ('substitute_to', models.DateTimeField(blank=True, null=True, verbose_name='Заместитель до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='account.department', verbose_name='Ответственный отдел')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('eco_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='ecopark.ecoobject', verbose_name='Объект')),
                ('substitute_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_routes', to=settings.AUTH_USER_MODEL, verbose_name='Заместитель')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('custom', 'Произвольно')], default='daily', max_length=16, verbose_name='Частота')),
                ('interval_hours', models.PositiveIntegerField(default=24, verbose_name='Интервал')),
                ('window_hours', models.PositiveIntegerField(default=2, verbose_name='Временное окно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ecopark.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Расписание маршрута',
                'verbose_name_plural': 'Расписания маршрутов',
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='ecopark.roundpoint', verbose_name='QR-точка')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='ecopark.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'point')},
            },
        ),
        migrations.CreateModel(
            name='PlannedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('missed', 'Пропущен')], default='pending', max_length=16, verbose_name='Статус')),
                ('planned_start', models.DateTimeField(verbose_name='Плановое начало')),
                ('planned_end', models.DateTimeField(verbose_name='Плановый конец (окно)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_rounds', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_rounds', to='ecopark.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Плановый обход',
                'verbose_name_plural': 'Плановые обходы',
                'ordering': ['-planned_start'],
                'unique_together': {('route', 'planned_start')},
            },
        ),
    ]
