# Generated by Django 4.2.17 on 2026-06-05 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_tenant_date_notify'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_tenant_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField(choices=[('electrical', 'Электрика'), ('plumbing', 'Сантехника'), ('hvac', 'Вентиляция и кондиционирование'), ('cleaning', 'Клининг'), ('furniture', 'Мебель и фурнитура'), ('it', 'ИТ и связь'), ('security', 'Безопасность'), ('other', 'Прочее')], default='other', verbose_name='Категория')),
                ('title', models.CharField(max_length=160, verbose_name='Тема')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание проблемы')),
                ('room', models.CharField(blank=True, max_length=60, null=True, verbose_name='Помещение / локация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=project.utils.PathAndRename('tickets/'), verbose_name='Фото')),
                ('priority', models.SlugField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', verbose_name='Приоритет')),
                ('status', models.SlugField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='account.department', verbose_name='Отдел')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='tenants.tenant', verbose_name='Арендатор')),
            ],
            options={
                'verbose_name': 'Сервисная заявка',
                'verbose_name_plural': 'Сервисные заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SlugField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.servicerequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История сервисной заявки',
                'verbose_name_plural': 'История сервисных заявок',
                'ordering': ['-id'],
            },
        ),
    ]
