# Generated by Django 4.2.17 on 2026-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Оригинальное имя файла'),
        ),
    ]
