# Generated by Django 4.2.17 on 2026-08-11 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticketattachment_original_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.SlugField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('pending_approval', 'На согласовании'), ('approved', 'Согласовано'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='servicerequesthistory',
            name='status',
            field=models.SlugField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('pending_approval', 'На согласовании'), ('approved', 'Согласовано'), ('done', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TicketTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=64, unique=True, verbose_name='Тип заявки')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требует согласования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автоназначение на')),
            ],
            options={
                'verbose_name': 'Настройка типа заявки',
                'verbose_name_plural': 'Настройки типов заявок',
            },
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Согласовано'), ('reject', 'Отклонено')], max_length=16, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял решение')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to='tickets.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Решение по согласованию',
                'verbose_name_plural': 'Решения по согласованию',
                'ordering': ['-created_at'],
            },
        ),
    ]
