# Generated by Django 4.2.17 on 2026-08-12 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_employeestatuslog'),
        ('tickets', '0005_alter_servicerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettypeconfig',
            options={'ordering': ['ticket_type', 'department_id'], 'verbose_name': 'Настройка типа заявки', 'verbose_name_plural': 'Настройки типов заявок'},
        ),
        migrations.AddField(
            model_name='tickettypeconfig',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Пусто — настройка действует для всех отделов по умолчанию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_configs', to='account.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='tickettypeconfig',
            name='sla_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Срок на обработку заявки этого типа. Пусто — SLA не задан.', null=True, verbose_name='SLA, часов'),
        ),
        migrations.AddField(
            model_name='tickettypeconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tickettypeconfig',
            name='ticket_type',
            field=models.CharField(max_length=64, verbose_name='Тип заявки'),
        ),
        migrations.AddConstraint(
            model_name='tickettypeconfig',
            constraint=models.UniqueConstraint(fields=('ticket_type', 'department'), name='unique_tickettypeconfig_type_department'),
        ),
    ]
