# Generated by Django 4.2.17 on 2026-08-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_tickettypeconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettypeconfig',
            name='ticket_type',
            field=models.CharField(choices=[('electrical', 'Электрика'), ('plumbing', 'Сантехника'), ('hvac', 'Вентиляция и кондиционирование'), ('cleaning', 'Клининг'), ('furniture', 'Мебель и фурнитура'), ('it', 'ИТ и связь'), ('security', 'Безопасность'), ('other', 'Прочее')], max_length=64, verbose_name='Тип заявки'),
        ),
    ]
